version: '2'

services:
    traefik:
        image: foobox/traefik:1.7.12-amd64
        ports:
            - "§TRAEFIK_HTTP_ENTRYPOINT_ADDRESS:80"
            - "$TRAEFIK_HTTPS_ENTRYPOINT_ADDRESS:443"
            - "$TRAEFIK_ADMIN_ENTRYPOINT_ADDRESS:8000"
        labels:
            io.rancher.scheduler.global: "true"
            io.rancher.scheduler.affinity:host_label: traefik_lb=true
            io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
            io.rancher.container.agent.role: environment
            io.rancher.container.create_agent: "true"
        environment:
            TRAEFIK_ACME_EMAIL: $TRAEFIK_ACME_EMAIL
            TRAEFIK_ACME_ENABLE: $TRAEFIK_ACME_ENABLE
            TRAEFIK_ACME_KEYTYPE: $TRAEFIK_ACME_KEYTYPE
            TRAEFIK_ADMIN_AUTH_USERS: TRAEFIK_ADMIN_AUTH_USERS
            TRAEFIK_API_ENABLE: $TRAEFIK_ADMIN_ENABLE
            TRAEFIK_API_STATISTICS: $TRAEFIK_API_STATISTICS
            TRAEFIK_COMPRESSION: $TRAEFIK_COMPRESSION
            TRAEFIK_HTTPS_ADDRESS: $TRAEFIK_HTTPS_ADDRESS
            TRAEFIK_HTTPS_ENABLE: $TRAEFIK_HTTPS_ENABLE
            TRAEFIK_HTTP_ADDRESS: $TRAEFIK_HTTP_ADDRESS
            TRAEFIK_METRICS_ENABLE: $TRAEFIK_METRICS_ENABLE
            TRAEFIK_PING_ENABLE: "true"
            TRAEFIK_TLS_VERSION_MIN: $TRAEFIK_TLS_VERSION_MIN
        volumes:
            - $TRAEFIK_ACME_VOLUME:/etc/traefik/acme

volumes:
    $TRAEFIK_ACME_VOLUME:
