version: '2'

services:
    openssh-server:
        scale: 1
        start_on_create: true
        health_check:
            response_timeout: 2000
            healthy_threshold: 2
            port: 22
            unhealthy_threshold: 3
            initializing_timeout: 60000
            interval: 10000
            strategy: recreate
            reinitializing_timeout: 60000

catalog:
    name: OpenSSH-Server
    version: 7.7.0
    description: 'OpenSSH-Server'
    minimum_rancher_version: 1.6.17
    questions:
    -   variable: OPENSSH_SERVER_PORT
        label: Public port
        type: int
        required: true
        default: "222"

    -   variable: OPENSSH_SERVER_PASSWORD_ALLOW
        label: Allow passwort authentication
        type: boolean
        required: true
        default: "false"

    -   variable: OPENSSH_SERVER_BANNER
        label: Banner
        description: Show Message when connecting to the server
        type: multiline
        required: false

    -   variable: OPENSSH_SERVER_MOTD
        label: Motd
        description: Show Message when login to the server
        type: multiline
        required: false

    -   variable: OPENSSH_SERVER_USER_NAMES
        label: User names
        description: Create users. One user name per line.
        type: multiline
        required: false

    -   variable: OPENSSH_REMOTE_KEYS_URL
        label: Fetch public keys from this url
        description: $u is a placeholder for the user name e.g. https://gitlab.example.com/%u.keys
        type: string
        required: false
