version: "2"

services:

    pagespeed:
        image: foobox/nginx-pagespeed:1.13.35
        environment:
            NGINX_RESOLVERS: "169.254.169.250"
            NGINX_RESOLVER_VALID: "5s"
            NGINX_RESOLVER_TIMEOUT: "5s"
            PAGESPEED_UPSTREAM_HOST: "nginx-reverse-proxy"
            PAGESPEED_PROXY_HOST: $NGINX_PROXY_HOST
            PAGESPEED_DOMAINS: $PAGESPEED_DOMAINS
            PAGESPEED_REWRITE_LEVEL: $PAGESPEED_REWRITE_LEVEL
            PAGESPEED_FILTERS_ENABLE: $PAGESPEED_FILTERS_ENABLE
            PAGESPEED_FILTERS_DISABLE: $PAGESPEED_FILTERS_DISABLE
            PAGESPEED_MAP_ORIGIN_DOMAIN: $NGINX_HOST
            NGINX_CLIENT_BODY_SIZE_MAX: $NGINX_CLIENT_BODY_SIZE_MAX
            NGINX_PROXY_READ_TIMEOUT: $NGINX_PROXY_READ_TIMEOUT
            NGINX_PROXY_SEND_TIMEOUT: $NGINX_PROXY_SEND_TIMEOUT
            NGINX_SEND_TIMEOUT: $NGINX_SEND_TIMEOUT
        labels:
            traefik.enable: $TRAEFIK_ENABLE
            traefik.port: "80"
            traefik.frontend.rule: $TRAEFIK_HOST
            traefik.frontend.priority: "10"
            traefik.frontend.headers.SSLRedirect: $TRAEFIK_HTTPS_REDIRECT
            traefik.frontend.headers.STSPreload: "true"
            traefik.frontend.headers.STSSeconds: "315360000"
            traefik.frontend.headers.browserXSSFilter: "true"
            traefik.frontend.headers.contentTypeNosniff: "true"
            traefik.frontend.headers.forceSTSHeader: "false"
            traefik.frontend.headers.frameDeny: "false"
            traefik.frontend.headers.referrerPolicy: "origin-when-cross-origin"
            {{- if eq .Values.TRAEFIK_ERROR_ENABLE "true" }}
            traefik.frontend.errors.5xx.backend: $TRAEFIK_ERROR_BACKEND
            traefik.frontend.errors.5xx.status: $TRAEFIK_ERROR_STATUS
            traefik.frontend.errors.5xx.query: $TRAEFIK_ERROR_QUERY
            {{- end }}

    nginx-reverse-proxy:
        image: foobox/nginx-reverse-proxy:1.14.2
        environment:
            NGINX_RESOLVERS: "169.254.169.250"
            NGINX_RESOLVER_VALID: "5s"
            NGINX_RESOLVER_TIMEOUT: "5s"
            NGINX_UPSTREAM_SERVICE: $NGINX_UPSTREAM_SERVICE
            NGINX_PROXY_HOST: $NGINX_PROXY_HOST
            NGINX_CLIENT_BODY_SIZE_MAX: $NGINX_CLIENT_BODY_SIZE_MAX
            NGINX_PROXY_READ_TIMEOUT: $NGINX_PROXY_READ_TIMEOUT
            NGINX_PROXY_SEND_TIMEOUT: $NGINX_PROXY_SEND_TIMEOUT
            NGINX_SEND_TIMEOUT: $NGINX_SEND_TIMEOUT
        labels:
            traefik.enable: "false"
            traefik.port: "80"
            traefik.frontend.rule: $TRAEFIK_HOST
            traefik.frontend.priority: "5"
            traefik.frontend.headers.SSLRedirect: $TRAEFIK_HTTPS_REDIRECT
            traefik.frontend.headers.STSPreload: "true"
            traefik.frontend.headers.STSSeconds: "315360000"
            traefik.frontend.headers.browserXSSFilter: "true"
            traefik.frontend.headers.contentTypeNosniff: "true"
            traefik.frontend.headers.forceSTSHeader: "false"
            traefik.frontend.headers.frameDeny: "false"
            traefik.frontend.headers.referrerPolicy: "origin-when-cross-origin"
