version: "2"

services:

    web:
        image: foobox/wordpress:4.9-web
        environment:
            MYSQL_USER: $MYSQL_USER
            MYSQL_PASSWORD: $MYSQL_PASSWORD
            MYSQL_DATABASE: $MYSQL_DATABASE
            WORDPRESS_FILE_EDIT_ENABLE: $WORDPRESS_FILE_EDIT_ENABLE
            WORDPRESS_FILE_MODS_ENABLE: $WORDPRESS_FILE_MODS_ENABLE
            WORDPRESS_CRON_ENABLE: $WORDPRESS_CRON_ENABLE
            WORDPRESS_CACHE: $WORDPRESS_CACHE
        volumes:
            - wordpress-content:/var/www/html/htdocs/wp-content
        labels:
            traefik.enable: $TRAEFIK_ENABLE
            traefik.port: "80"
            traefik.frontend.rule: $TRAEFIK_HOST
            traefik.frontend.headers.SSLRedirect: "true"
            traefik.frontend.headers.STSPreload: "true"
            traefik.frontend.headers.STSSeconds: "315360000"
            traefik.frontend.headers.browserXSSFilter: "true"
            traefik.frontend.headers.contentTypeNosniff: "true"
            traefik.frontend.headers.forceSTSHeader: "false"
            traefik.frontend.headers.frameDeny: "true"
            traefik.frontend.headers.referrerPolicy: "origin-when-cross-origin"


    cron:
        image: foobox/wordpress:4.9-cli
        environment:
            MYSQL_USER: $MYSQL_USER
            MYSQL_PASSWORD: $MYSQL_PASSWORD
            MYSQL_DATABASE: $MYSQL_DATABASE
            WORDPRESS_FILE_EDIT_ENABLE: $WORDPRESS_FILE_EDIT_ENABLE
            WORDPRESS_FILE_MODS_ENABLE: $WORDPRESS_FILE_MODS_ENABLE
            WORDPRESS_CRON_ENABLE: $WORDPRESS_CRON_ENABLE
            WORDPRESS_CACHE: $WORDPRESS_CACHE
        volumes:
            - wordpress-content:/var/www/html/htdocs/wp-content
        labels:
            io.rancher.container.start_once: 'true'
            cron.schedule: '@every 5m'

    mysql:
        image: foobox/mariadb-server:10.2.15
        environment:
            MYSQL_USER: $MYSQL_USER
            MYSQL_PASSWORD: $MYSQL_PASSWORD
            MYSQL_DATABASE: $MYSQL_DATABASE
            MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
        volumes:
            - mariadb-data:/var/lib/mysql

    memcache:
        image: foobox/memcache-server:1.5

volumes:
    wordpress-content:
    mariadb-data:
