version: '2'

services:

    openssh-server:
        scale: 1
        start_on_create: true
        health_check:
            response_timeout: 2000
            healthy_threshold: 2
            port: 22
            unhealthy_threshold: 3
            initializing_timeout: 60000
            interval: 2000
            strategy: recreate
            reinitializing_timeout: 60000
