version: '2'

services:
    hetzner-volume:
        privileged: true
        image: foobox/hetzner-volume-rancher
        environment:
            HETZNER_API_KEY: $HETZNER_API_KEY
            HETZNER_VOLUME_PREFIX: $HETZNER_VOLUME_PREFIX
        network_mode: host
        volumes:
            - /var/run:/var/run
            - /dev:/dev
            - /var/lib/rancher/volumes/hetzner:/var/lib/rancher/volumes/hetzner:shared
        labels:
            io.rancher.container.agent.role: environment,agent
            io.rancher.container.create_agent: 'true'
            io.rancher.scheduler.global: 'true'
