version: '2'

services:
    hetzner-volume:
        privileged: true
        image: alpine:3.11
        command: sleep 3600
        labels:
            io.rancher.scheduler.global: 'true'
            io.rancher.container.create_agent: 'true'
            io.rancher.container.agent.role: environment
            io.rancher.container.dns: 'true'
