version: '2'

services:
    hetzner-volume:
        privileged: true
        image: costela/docker-volume-hetzner:0.1.4
        labels:
            io.rancher.scheduler.global: 'true'
            io.rancher.container.create_agent: 'true'
            io.rancher.container.agent.role: environment
            io.rancher.container.dns: 'true'
