version: '2'

services:
    hetzner-volume:
        privileged: true
        image: foobox/hetzner-volume-rancher
        labels:
            io.rancher.scheduler.global: 'true'
            io.rancher.container.create_agent: 'true'
            io.rancher.container.agent.role: environment
            io.rancher.container.dns: 'true'
