version: '2'

hetzner-volume:
    secrets-driver:
        storage_driver:
            description: hetzner driver
            name: hetzner
            scope: environment
            volumeAccessMode: singleHostRW
        start_on_create: true

