version: '2'

services:
    hetzner-volume:
        storage_driver:
            description: hetzner driver
            name: hetzner
            scope: environment
            volumeAccessMode: singleHostRW
        start_on_create: true

