version: '2'

services:
    rancher-traefik-sync:
        image: foobox/rancher-traefik-sync:latest
        environment:
            RANCHER_URL: $RANCHER_URL
            RANCHER_USERNAME: $RANCHER_USERNAME
            RANCHER_PASSWORD: $RANCHER_PASSWORD
        volumes:
            - traefik_acme_vol:/mnt
        labels:
            io.rancher.container.start_once: 'true'
            io.rancher.container.pull_image: always
            cron.schedule: '@every 1h'
