version: '2'

services:

    memcached:
        scale: 1
        start_on_create: true

catalog:
    name: memcached
    version: 1.0.0
    description: Send mail
    minimum_rancher_version: 1.6.7
    questions:
        - variable: MEMCACHED_MEMORY_LIMIT
          label: "Memory limit"
          require: true
          default: 64
          type: "int"
