version: '2'

services:

    rancher-traefik-sync:
        scale: 1
        start_on_create: true

catalog:
    name: rancher-traefik-sync
    version: 1.1.0
    description: Sync certificates from Traefik to the certificate storage in Rancher.
    minimum_rancher_version: 1.6.7
    questions:
        - variable: RANCHER_URL
          label: "Rancher URL"
          required: false
          type: "string"
          description: "Default $CATTLE_URL"

        - variable: RANCHER_USERNAME
          label: "Rancher Username"
          required: false
          type: "string"
          description: "Default $CATTLE_ACCESS_KEY"

        - variable: RANCHER_PASSWORD
          label: "Rancher Password"
          required: false
          type: "password"
          description: "Default $CATTLE_SECRET_KEY"

        - variable: TRAEFIK_ACME_VOLUME
          label: "Traefik ACME Volume"
          required: true
          type: "string"
          default: "traefik_acme_vol"
