version: '2'

services:

    rancher-traefik-sync:
        scale: 1
        start_on_create: true

catalog:
    name: rancher-traefik-sync
    version: 1.1.0
    description: Sync certificates from Traefik to the certificate storage in Rancher.
    minimum_rancher_version: 1.6.7
    questions:
        - variable: TRAEFIK_ACME_VOLUME
          label: "Traefik ACME Volume"
          required: true
          type: "string"
          default: "traefik_acme_vol"
