version: '2'

services:

    system-prune:
        image: foobox/docker-client:18.09.6
        command: system prune --force --all --filter "until=72h"
        labels:
            io.rancher.scheduler.global: "true"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
