version: "2"

services:
    traefik:
        image: foobox/traefik:2.4.9
        ports:
            - 80:80/tcp
            - 443:443/tcp
        volumes:
            - traefik-acme:/etc/traefik/acme
        labels:
            io.rancher.scheduler.global: "true"
            io.rancher.scheduler.affinity:host_label: traefik_lb=true
        environment:
            TRAEFIK_GLOBAL_CHECKNEWVERSION: "false"
            TRAEFIK_GLOBAL_SENDANONYMOUSUSAGE: "false"
            TRAEFIK_PILOT_DASHBOARD: "false"
            TRAEFIK_LOG: "true"
            TRAEFIK_LOG_FILEPATH: /dev/stderr
            TRAEFIK_ACCESSLOG: $TRAEFIK_ACCESSLOG
            TRAEFIK_PING: "true"
            TRAEFIK_API: "false"
            TRAEFIK_API_INSECURE: "false"
            TRAEFIK_PROVIDERS_RANCHER: "true"
            TRAEFIK_PROVIDERS_RANCHER_EXPOSEDBYDEFAULT: "false"
            TRAEFIK_CERTIFICATESRESOLVERS_LETSENCRYPT: $TRAEFIK_CERTIFICATESRESOLVERS_LETSENCRYPT
            TRAEFIK_CERTIFICATESRESOLVERS_LETSENCRYPT_ACME_CASERVER: https://acme-v02.api.letsencrypt.org/directory
            TRAEFIK_CERTIFICATESRESOLVERS_LETSENCRYPT_ACME_STORAGE: /etc/traefik/acme/letsencrypt.json
            TRAEFIK_CERTIFICATESRESOLVERS_LETSENCRYPT_ACME_KEYTYPE: $TRAEFIK_CERTIFICATESRESOLVERS_LETSENCRYPT_ACME_KEYTYPE
            TRAEFIK_CERTIFICATESRESOLVERS_LETSENCRYPT_ACME_EMAIL: $TRAEFIK_CERTIFICATESRESOLVERS_LETSENCRYPT_ACME_EMAIL
            TRAEFIK_CERTIFICATESRESOLVERS_LETSENCRYPT_ACME_HTTPCHALLENGE: "true"
            TRAEFIK_CERTIFICATESRESOLVERS_LETSENCRYPT_ACME_HTTPCHALLENGE_ENTRYPOINT: http
            TRAEFIK_ENTRYPOINTS_HTTP: "true"
            TRAEFIK_ENTRYPOINTS_HTTP_ADDRESS: :80
            TRAEFIK_ENTRYPOINTS_HTTP_HTTP_MIDDLEWARES: TRAEFIK_ENTRYPOINTS_HTTP_HTTP_MIDDLEWARES
            TRAEFIK_ENTRYPOINTS_HTTP_HTTP_TLS: "false"
            TRAEFIK_ENTRYPOINTS_HTTPS: $TRAEFIK_ENTRYPOINTS_HTTPS
            TRAEFIK_ENTRYPOINTS_HTTPS_ADDRESS: :443
            TRAEFIK_ENTRYPOINTS_HTTPS_HTTP_MIDDLEWARES: TRAEFIK_ENTRYPOINTS_HTTPS_HTTP_MIDDLEWARES
            TRAEFIK_ENTRYPOINTS_HTTPS_HTTP_TLS: "true"
            TRAEFIK_ENTRYPOINTS_HTTPS_HTTP_TLS_CERTRESOLVER: letsencrypt
