version: "2"
services:
    convoy-nfs:
        image: rancher/convoy-agent:v0.12.0
        command: volume-agent-nfs
        volumes:
            - /lib/modules:/lib/modules:ro
            - /proc:/host/proc
            - /var/run:/host/var/run
            - /run:/host/run
            - /etc/docker/plugins:/etc/docker/plugins
        labels:
            io.rancher.container.create_agent: 'true'
            io.rancher.scheduler.global: 'true'
        privileged: true
        pid: host

    convoy-nfs-storagepool:
        image: rancher/convoy-agent:v0.12.0
        command: storagepool-agent
        volumes:
            - /var/run:/host/var/run
            - /run:/host/run
        labels:
            io.rancher.container.create_agent: 'true'
