version: '2'

services:
    postfix:
        image: foobox/postfix:latest
        environment:
            POSTFIX_DOMAIN: $POSTFIX_DOMAIN
        volumes:
            - postfix-spool:/var/spool/postfix
        labels:
            io.rancher.container.pull_image: always
