version: '2'

services:

    web:
        image: foobox/wordpress:latest-web
        environment:
            MYSQL_USER: $MYSQL_USER
            MYSQL_PASSWORD: $MYSQL_PASSWORD
            MYSQL_DATABASE: $MYSQL_DATABASE
            WORDPRESS_FILE_EDIT_ENABLE: $WORDPRESS_FILE_EDIT_ENABLE
            WORDPRESS_FILE_MODS_ENABLE: $WORDPRESS_FILE_MODS_ENABLE
            WORDPRESS_CRON_ENABLE: $WORDPRESS_CRON_ENABLE
            WORDPRESS_CACHE: $WORDPRESS_CACHE
        volumes:
            - wordpress-content:/var/www/html/htdocs/wp-content
        labels:
            io.rancher.container.pull_image: always
            traefik.frontend.rule: $TRAEFIK_HOST
            traefik.port: '80'
            traefik.enable: $TRAEFIK_ENABLE

    cron:
        image: foobox/wordpress:latest-cli
        environment:
            MYSQL_USER: $MYSQL_USER
            MYSQL_PASSWORD: $MYSQL_PASSWORD
            MYSQL_DATABASE: $MYSQL_DATABASE
            WORDPRESS_FILE_EDIT_ENABLE: $WORDPRESS_FILE_EDIT_ENABLE
            WORDPRESS_FILE_MODS_ENABLE: $WORDPRESS_FILE_MODS_ENABLE
            WORDPRESS_CRON_ENABLE: $WORDPRESS_CRON_ENABLE
            WORDPRESS_CACHE: $WORDPRESS_CACHE
        volumes:
            - wordpress-content:/var/www/html/htdocs/wp-content
        labels:
            io.rancher.container.pull_image: always
            io.rancher.container.start_once: 'true'
            cron.schedule: '@every 5m'

    mysql:
        image: foobox/mariadb:10.1
        environment:
            MYSQL_USER: $MYSQL_USER
            MYSQL_PASSWORD: $MYSQL_PASSWORD
            MYSQL_DATABASE: $MYSQL_DATABASE
            MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
        volumes:
            - mariadb-data:/var/lib/mysql
        labels:
            io.rancher.container.pull_image: always

    memcache:
        image: foobox/memcached:1.5
        labels:
            io.rancher.container.pull_image: always
        
volumes:
    wordpress-content:
    mariadb-data:
