version: '2'

services:

    web:
        image: foobox/wordpress:latest-web
        environment:
            WORDPRESS_FILE_EDIT_ENABLE: $WORDPRESS_FILE_EDIT_ENABLE
            WORDPRESS_FILE_MODS_ENABLE: $WORDPRESS_FILE_MODS_ENABLE
            WORDPRESS_CRON_ENABLE: $WORDPRESS_CRON_ENABLE
            MYSQL_USER: $MYSQL_USER
            MYSQL_PASSWORD: $MYSQL_PASSWORD
            MYSQL_DATABASE: $MYSQL_DATABASE
        volumes:
            - wordpress-content:/var/lib/mysql
        labels:
            io.rancher.container.pull_image: always

    cron:
        image: foobox/wordpress:latest-cli
        environment:
            MYSQL_USER: $MYSQL_USER
            MYSQL_PASSWORD: $MYSQL_PASSWORD
            MYSQL_DATABASE: $MYSQL_DATABASE
        volumes:
            - wordpress-content:/var/lib/mysql
        labels:
            io.rancher.container.pull_image: always
            io.rancher.container.start_once: 'true'
            cron.schedule: '@every 5m'

    mysql:
        image: mysql:5.7
        environment:
            MYSQL_USER: $MYSQL_USER
            MYSQL_PASSWORD: $MYSQL_PASSWORD
            MYSQL_DATABASE: $MYSQL_DATABASE
            MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
        volumes:
            - mysql-data:/var/lib/mysql
        labels:
            io.rancher.container.pull_image: always

    memcache:
        image: foobox/memcached:1.5
        labels:
            io.rancher.container.pull_image: always
        
volumes:
    wordpress-content:
    mysql-data:
