version: '2'

services:
    traefik:
        image: foobox/traefik:2.0.1-amd64
        ports:
            - "80:80"
            - "443:443"
            - "8080:8080"
        environment:
            TRAEFIK_ACCESSLOG: $TRAEFIK_ACCESSLOG
            TRAEFIK_ACCESSLOG_BUFFERINGSIZE: $TRAEFIK_ACCESSLOG_BUFFERINGSIZE
            TRAEFIK_ACCESSLOG_FILTERS_MINDURATION: $TRAEFIK_ACCESSLOG_FILTERS_MINDURATION
            TRAEFIK_ACCESSLOG_FILTERS_RETRYATTEMPTS: $TRAEFIK_ACCESSLOG_FILTERS_RETRYATTEMPTS
            TRAEFIK_ACCESSLOG_FILTERS_STATUSCODES: $TRAEFIK_ACCESSLOG_FILTERS_STATUSCODES
            TRAEFIK_API: $TRAEFIK_API
            TRAEFIK_API_DASHBOARD: $TRAEFIK_API_DASHBOARD
            TRAEFIK_API_DEBUG: $TRAEFIK_API_DEBUG
            TRAEFIK_API_INSECURE: $TRAEFIK_API_INSECURE
            TRAEFIK_CERTIFICATESRESOLVERS_LETSENCRYPT: $TRAEFIK_CERTIFICATESRESOLVERS_LETSENCRYPT
            TRAEFIK_CERTIFICATESRESOLVERS_LETSENCRYPT_ACME_CASERVER: $TRAEFIK_CERTIFICATESRESOLVERS_LETSENCRYPT_ACME_CASERVER
            TRAEFIK_CERTIFICATESRESOLVERS_LETSENCRYPT_ACME_EMAIL: $TRAEFIK_CERTIFICATESRESOLVERS_LETSENCRYPT_ACME_EMAIL
            TRAEFIK_CERTIFICATESRESOLVERS_LETSENCRYPT_ACME_HTTPCHALLENGE: $TRAEFIK_CERTIFICATESRESOLVERS_LETSENCRYPT_ACME_HTTPCHALLENGE
            TRAEFIK_CERTIFICATESRESOLVERS_LETSENCRYPT_ACME_ENTRYPOINT: $TRAEFIK_CERTIFICATESRESOLVERS_LETSENCRYPT_ACME_ENTRYPOINT
            TRAEFIK_CERTIFICATESRESOLVERS_LETSENCRYPT_ACME_KEYTYPE: $TRAEFIK_CERTIFICATESRESOLVERS_LETSENCRYPT_ACME_KEYTYPE
            TRAEFIK_CERTIFICATESRESOLVERS_LETSENCRYPT_ACME_STORAGE: $TRAEFIK_CERTIFICATESRESOLVERS_LETSENCRYPT_ACME_STORAGE
            TRAEFIK_ENTRYPOINTS_HTTP: $TRAEFIK_ENTRYPOINTS_HTTP
            TRAEFIK_ENTRYPOINTS_HTTP_ADDRESS: $TRAEFIK_ENTRYPOINTS_HTTP_ADDRESS
            TRAEFIK_ENTRYPOINTS_HTTPS: $TRAEFIK_ENTRYPOINTS_HTTPS
            TRAEFIK_ENTRYPOINTS_HTTPS_ADDRESS: $TRAEFIK_ENTRYPOINTS_HTTPS_ADDRESS
            TRAEFIK_LOG: $TRAEFIK_LOG
            TRAEFIK_LOG_LEVEL: $TRAEFIK_LOG_LEVEL
            TRAEFIK_PING: $TRAEFIK_PING
            TRAEFIK_PROVIDERS_PROVIDERSTHROTTLEDURATION: $TRAEFIK_PROVIDERS_PROVIDERSTHROTTLEDURATION
            TRAEFIK_PROVIDERS_RANCHER: $TRAEFIK_PROVIDERS_RANCHER
            TRAEFIK_PROVIDERS_RANCHER_DEFAULTRULE: $TRAEFIK_PROVIDERS_RANCHER_DEFAULTRULE
            TRAEFIK_PROVIDERS_RANCHER_ENABLESERVICEHEALTHFILTER: $TRAEFIK_PROVIDERS_RANCHER_ENABLESERVICEHEALTHFILTER
            TRAEFIK_PROVIDERS_RANCHER_EXPOSEDBYDEFAULT: $TRAEFIK_PROVIDERS_RANCHER_EXPOSEDBYDEFAULT
            TRAEFIK_PROVIDERS_RANCHER_INTERVALPOLL: $TRAEFIK_PROVIDERS_RANCHER_INTERVALPOLL
            TRAEFIK_PROVIDERS_RANCHER_PREFIX: $TRAEFIK_PROVIDERS_RANCHER_PREFIX
            TRAEFIK_PROVIDERS_RANCHER_REFRESHSECONDS: $TRAEFIK_PROVIDERS_RANCHER_REFRESHSECONDS
            TRAEFIK_PROVIDERS_RANCHER_WATCH: $TRAEFIK_PROVIDERS_RANCHER_WATCH
        labels:
            io.rancher.scheduler.global: "true"
            io.rancher.scheduler.affinity:host_label: traefik_lb=true
            io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
            io.rancher.container.agent.role: environment
            io.rancher.container.create_agent: "true"
        volumes:
            - traefik_acme_vol:/etc/traefik/acme

volumes:
    traefik_acme_vol:
