version: '2'

catalog:
    name: "traefik"
    version: "v2.0.1-foobox1"
    description: "Traefik load balancer."
    minimum_rancher_version: v0.59.0
    questions:
        - variable: "TRAEFIK_ACCESSLOG"
          label: "Enable access log."
          description: "Access log settings."
          default: "true"
          type: "boolean"

        - variable: "TRAEFIK_ACCESSLOG_BUFFERINGSIZE"
          label: "Access log buffer size."
          description: "Number of access log lines to process in a buffered way."
          default: "0"
          type: "int"

        - variable: "TRAEFIK_ACCESSLOG_FILTERS_MINDURATION"
          label: "Keep access logs when request took longer than the specified duration."
          description: "Seconds"
          default: "0"
          type: "int"

        - variable: "TRAEFIK_ACCESSLOG_FILTERS_RETRYATTEMPTS"
          label: "Keep access logs when at least one retry happened."
          description: "Retries"
          default: "false"
          type: "boolean"

        - variable: "TRAEFIK_ACCESSLOG_FILTERS_STATUSCODES"
          label: "Keep access logs with status codes in the specified range."
          description: "400-499, 500-599"
          type: "string"

        - variable: "TRAEFIK_API"
          label: "Enable api/dashboard."
          default: "false"
          type: "boolean"

        - variable: "TRAEFIK_API_DASHBOARD"
          label: "Activate dashboard."
          default: "true"
          type: "boolean"

        - variable: "TRAEFIK_API_DEBUG"
          label: "Enable additional endpoints for debugging and profiling."
          default: "false"
          type: "boolean"

        - variable: "TRAEFIK_API_INSECURE"
          label: "Activate API directly on the entryPoint named traefik."
          default: "false"
          type: "boolean"

        - variable: "TRAEFIK_CERTIFICATESRESOLVERS_LETSENCRYPT"
          label: "Certificates resolvers configuration."
          default: "false"
          type: "boolean"

        - variable: "TRAEFIK_CERTIFICATESRESOLVERS_LETSENCRYPT_ACME_CASERVER"
          label: "CA server to use."
          default: "https://acme-v02.api.letsencrypt.org/directory"
          type: "string"

        - variable: "TRAEFIK_CERTIFICATESRESOLVERS_LETSENCRYPT_ACME_EMAIL"
          label: "Email address used for registration."
          type: "string"

        - variable: "TRAEFIK_CERTIFICATESRESOLVERS_LETSENCRYPT_ACME_HTTPCHALLENGE"
          label: "Activate HTTP-01 Challenge."
          default: "false"
          type: "boolean"

        - variable: "TRAEFIK_CERTIFICATESRESOLVERS_LETSENCRYPT_ACME_ENTRYPOINT"
          label: "HTTP challenge EntryPoint."
          type: "enum"
          default: "HTTP"
          options:
              - "HTTP"
              - "HTTPS"

        - variable: "TRAEFIK_CERTIFICATESRESOLVERS_LETSENCRYPT_ACME_KEYTYPE"
          label: "KeyType used for generating certificate private key."
          type: "enum"
          default: "RSA2048"
          options:
              - "EC384"
              - "EC256"
              - "RSA8192"
              - "RSA4096"
              - "RSA2048"

        - variable: "TRAEFIK_CERTIFICATESRESOLVERS_LETSENCRYPT_ACME_STORAGE"
          label: "Storage to use."
          type: "string"
          default: "/etc/traefik/acme/acme.json"

        - variable: "TRAEFIK_ENTRYPOINTS_HTTP"
          label: "Enable HTTP"
          default: "true"
          type: "boolean"

        - variable: "TRAEFIK_ENTRYPOINTS_HTTP_ADDRESS"
          label: "HTTP address."
          default: ":80"
          type: "string"

        - variable: "TRAEFIK_ENTRYPOINTS_HTTPS"
          label: "Enable HTTPS"
          default: "true"
          type: "boolean"

        - variable: "TRAEFIK_ENTRYPOINTS_HTTPS_ADDRESS"
          label: "HTTPS address."
          default: ":443"
          type: "string"

        - variable: "TRAEFIK_LOG"
          label: "Traefik log settings."
          default: "true"
          type: "boolean"

        - variable: "TRAEFIK_LOG_LEVEL"
          label: "Log level set to traefik logs."
          default: "WARNING"
          type: "enum"
          options:
              - "DEBUG"
              - "INFO"
              - "NOTICE"
              - "WARNING"
              - "ERROR"
              - "CRITICAL"

        - variable: "TRAEFIK_PING"
          label: "Enable ping."
          default: "true"
          type: "boolean"

        - variable: "TRAEFIK_PROVIDERS_PROVIDERSTHROTTLEDURATION"
          label: "Backends throttle duration: minimum duration between 2 events from providers before applying a new configuration."
          description: " It avoids unnecessary reloads if multiples events are sent in a short amount of time."
          default: "0"
          type: "int"

        - variable: "TRAEFIK_PROVIDERS_RANCHER"
          label: "Enable Rancher backend with default settings."
          default: "true"
          type: "boolean"

        - variable: "TRAEFIK_PROVIDERS_RANCHER_DEFAULTRULE"
          label: "Default rule."
          default: {{"Host(`{{ normalize .Name }}`)"}}
          type: "string"

        - variable: "TRAEFIK_PROVIDERS_RANCHER_ENABLESERVICEHEALTHFILTER"
          label: "Filter services with unhealthy states and inactive states."
          default: "true"
          type: "boolean"

        - variable: "TRAEFIK_PROVIDERS_RANCHER_EXPOSEDBYDEFAULT"
          label: "Expose containers by default."
          default: "false"
          type: "boolean"

        - variable: "TRAEFIK_PROVIDERS_RANCHER_INTERVALPOLL"
          label: "Poll the Rancher metadata service every 'rancher.refreshseconds' (less accurate)."
          default: "false"
          type: "boolean"

        - variable: "TRAEFIK_PROVIDERS_RANCHER_PREFIX"
          label: "Prefix used for accessing the Rancher metadata service."
          default: "latest"
          type: "string"

        - variable: "TRAEFIK_PROVIDERS_RANCHER_REFRESHSECONDS"
          label: "Defines the polling interval in seconds."
          default: "15"
          type: "int"

        - variable: "TRAEFIK_PROVIDERS_RANCHER_WATCH"
          label: "Watch provider"
          default: "true"
          type: "boolean"

services:
    traefik:
        drain_timeout_ms: 60000
        start_on_create: true
        upgrade_strategy:
            start_first: true
        health_check:
            healthy_threshold: 2
            response_timeout: 1000
            port: 8080
            unhealthy_threshold: 3
            initializing_timeout: 10000
            interval: 10000
            strategy: recreate
            request_line: GET "/ping" "HTTP/1.0"
            reinitializing_timeout: 10000
